### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by boyfromhell** [gpasztor87/oc-notifications-plugin#1]
`Trying to get property of non-object" on line 16 of F:\wamp64-gt\www\my-site\plugins\autumn\notifications\classes\Notification.php`

**Comment by gpasztor87** [comment]
Hi!

You should register notifications by calling the Plugin.php registerNotifications() function.
Maybe this step is missing from your code.

Cheers!

**Comment by boyfromhell** [comment]
The error that appears to me is that https://github.com/gpasztor87/oc-social-plugin,
that is placed on you.
I tried with your theme.

**Comment by boyfromhell** [comment]
So then I downloaded:
https://github.com/gpasztor87/oc-messages-plugin
https://github.com/gpasztor87/oc-social-theme
https://github.com/gpasztor87/oc-social-plugin
https://github.com/gpasztor87/oc-notifications-plugin
I installed.
When I write a review I give that error.
`Trying to get property of non-object" on line 16 of F:\wamp64-gt\www\my-site\plugins\autumn\notifications\classes\Notification.php`

**Comment by gpasztor87** [comment]
Yes, It's because I forgot to add this file to my github repo:
https://github.com/gpasztor87/oc-social-plugin/blob/master/Plugin.php#L57

Just comment this, and I've be fix it shortly.

**Comment by boyfromhell** [comment]
So.
It's not good
https://github.com/boyfromhell/oc-social-plugin/blob/master/Notifications/CommentPosted.php#L1
